name: Test
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
