on: pull_request
jobs:
  arrange:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: go get github.com/jdeflander/goarrange
        working-directory: ${{ runner.temp }}
      - run: test -z "$(goarrange run -r -d)"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39
          args: -E misspell,godot,whitespace

  test:
    strategy:
      matrix:
        go-version: [ 1.15.x, 1.16.x ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v ./...

  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: go mod tidy
      - run: git diff --quiet go.mod go.sum
